# This file was auto-generated by Fern from our API Definition.

import typing
from ...types.tool_choice import ToolChoice

PromptLogRequestToolChoice = typing.Union[
    typing.Literal["none"], typing.Literal["auto"], typing.Literal["required"], ToolChoice
]
