# This file was auto-generated by Fern from our API Definition.

import typing_extensions
import typing_extensions
from .agent_continue_stream_response_payload import AgentContinueStreamResponsePayloadParams
from ..types.event_type import EventType
import datetime as dt


class AgentContinueStreamResponseParams(typing_extensions.TypedDict):
    """
    Response model for continuing an Agent call in streaming mode.
    """

    log_id: str
    message: str
    payload: typing_extensions.NotRequired[AgentContinueStreamResponsePayloadParams]
    type: EventType
    created_at: dt.datetime
