# This file was auto-generated by Fern from our API Definition.

import typing_extensions
import typing
from .linked_file_request import LinkedFileRequestParams


class AgentLinkedFileRequestParams(typing_extensions.TypedDict):
    type: typing.Literal["file"]
    link: LinkedFileRequestParams
