# This file was auto-generated by Fern from our API Definition.

import typing
from .agent_linked_file_request import AgentLinkedFileRequestParams
from .agent_inline_tool import AgentInlineToolParams

AgentKernelRequestToolsItemParams = typing.Union[AgentLinkedFileRequestParams, AgentInlineToolParams]
