# This file was auto-generated by Fern from our API Definition.

import typing_extensions

from ..types.feedback_label_status import FeedbackLabelStatus
from ..types.label_sentiment import LabelSentiment


class CategoricalFeedbackLabelParams(typing_extensions.TypedDict):
    value: str
    sentiment: LabelSentiment
    """
    Whether the feedback sentiment is positive or negative.
    """

    status: FeedbackLabelStatus
    """
    Whether the feedback label is active or inactive.
    """
