# This file was auto-generated by Fern from our API Definition.

import typing
from .text_chat_content import TextChatContentParams
from .image_chat_content import ImageChatContentParams

ChatMessageContentItemParams = typing.Union[TextChatContentParams, ImageChatContentParams]
