# This file was auto-generated by Fern from our API Definition.

import typing
from .chat_message_content_item import ChatMessageContentItemParams

ChatMessageContentParams = typing.Union[str, typing.Sequence[ChatMessageContentItemParams]]
