# This file was auto-generated by Fern from our API Definition.

import typing_extensions


class CommitRequestParams(typing_extensions.TypedDict):
    commit_message: str
    """
    Message describing the changes made.
    """
