# This file was auto-generated by Fern from our API Definition.

import typing
from .prompt_response import PromptResponseParams
from .tool_response import ToolResponseParams
from .evaluator_response import EvaluatorResponseParams
from .flow_response import FlowResponseParams

EvaluatedVersionResponseParams = typing.Union[
    PromptResponseParams, ToolResponseParams, EvaluatorResponseParams, FlowResponseParams
]
