# This file was auto-generated by Fern from our API Definition.

import typing
from .prompt_response import PromptResponseParams
from ..types.tool_response import ToolResponse
from .evaluator_response import EvaluatorResponseParams
from .flow_response import FlowResponseParams

EvaluatedVersionResponseParams = typing.Union[
    PromptResponseParams, ToolResponse, EvaluatorResponseParams, FlowResponseParams
]
