# This file was auto-generated by Fern from our API Definition.

import typing_extensions


class EvaluationsRequestParams(typing_extensions.TypedDict):
    version_id: str
    """
    Unique identifier for the Evaluator Version to use in this evaluation. Starts with `evv_`.
    """

    orchestrated: typing_extensions.NotRequired[bool]
    """
    Whether the Evaluator is orchestrated by Humanloop. Default is `True`. If `False`, a log for the Evaluator should be submitted by the user via the API.
    """
