# This file was auto-generated by Fern from our API Definition.

import typing_extensions


class FileEnvironmentVariableRequestParams(typing_extensions.TypedDict):
    name: str
    """
    Name of the environment variable.
    """

    value: str
    """
    Value of the environment variable.
    """
