# This file was auto-generated by Fern from our API Definition.

import typing_extensions


class FunctionToolChoiceParams(typing_extensions.TypedDict):
    """
    A function tool to be called by the model where user owns runtime.
    """

    name: str
