# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions


class LinkedToolRequestParams(typing_extensions.TypedDict):
    id: str
    """
    The ID of the linked tool. Starts with "oc\_"
    """

    source: typing.Literal["organization"]
    """
    The source of the linked tool. For a linked tool it should be `organization`
    """

    name: typing_extensions.NotRequired[str]
    """
    The name of the linked tool.
    """

    description: typing_extensions.NotRequired[str]
    """
    The description of the linked tool.
    """

    parameters: typing_extensions.NotRequired[typing.Dict[str, typing.Any]]
    """
    The parameters of the linked tool.
    """
