# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from .flow_response import FlowResponseParams


class ListFlowsParams(typing_extensions.TypedDict):
    records: typing.Sequence[FlowResponseParams]
    """
    The list of Flows.
    """
