# This file was auto-generated by Fern from our API Definition.

import typing

from .evaluator_log_response import EvaluatorLogResponseParams
from .prompt_log_response import PromptLogResponseParams
from .tool_log_response import ToolLogResponseParams

LogResponseParams = typing.Union[PromptLogResponseParams, ToolLogResponseParams, EvaluatorLogResponseParams]
