# This file was auto-generated by Fern from our API Definition.

import typing

from .agent_log_stream_response import AgentLogStreamResponseParams
from .prompt_call_stream_response import PromptCallStreamResponseParams

LogStreamResponseParams = typing.Union[PromptCallStreamResponseParams, AgentLogStreamResponseParams]
