# This file was auto-generated by Fern from our API Definition.

import typing_extensions


class MonitoringEvaluatorVersionRequestParams(typing_extensions.TypedDict):
    evaluator_version_id: str
    """
    Unique identifier for the Evaluator Version to be used for monitoring.
    """
