# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions

from ..types.tool_response import ToolResponse


class PaginatedDataToolResponseParams(typing_extensions.TypedDict):
    records: typing.Sequence[ToolResponse]
    page: int
    size: int
    total: int
