# This file was auto-generated by Fern from our API Definition.

import typing_extensions


class UserResponseParams(typing_extensions.TypedDict):
    id: str
    """
    Unique identifier for User. Starts with `usr`.
    """

    email_address: str
    """
    The User's email address.
    """

    full_name: typing_extensions.NotRequired[str]
    """
    The User's full name.
    """
