# coding: utf-8

"""
    Humanloop API

    The Humanloop API allows you to interact with Humanloop from your product or service.  You can do this through HTTP requests from any language or via our official Python or TypeScript SDK.  To install the official [Python SDK](https://pypi.org/project/humanloop/), run the following command:  ```bash pip install humanloop ```  To install the official [TypeScript SDK](https://www.npmjs.com/package/humanloop), run the following command:  ```bash npm i humanloop ```  ---  Guides and further details about key concepts can be found in [our docs](https://docs.humanloop.com/).

    The version of the OpenAPI document: 4.0.1
    Generated by: https://konfigthis.com
"""

from humanloop.paths.evaluations_id_evaluators.patch import AddEvaluatorsRaw
from humanloop.paths.projects_project_id_evaluations.post import CreateRaw
from humanloop.paths.evaluations_id.get import GetRaw
from humanloop.paths.evaluations.get import ListRaw
from humanloop.paths.projects_project_id_evaluations.get import ListAllForProjectRaw
from humanloop.paths.evaluations_id_datapoints.get import ListDatapointsRaw
from humanloop.paths.evaluations_evaluation_id_log.post import LogRaw
from humanloop.paths.evaluations_evaluation_id_result.post import ResultRaw
from humanloop.paths.evaluations_id_status.patch import UpdateStatusRaw


class EvaluationsApiRaw(
    AddEvaluatorsRaw,
    CreateRaw,
    GetRaw,
    ListRaw,
    ListAllForProjectRaw,
    ListDatapointsRaw,
    LogRaw,
    ResultRaw,
    UpdateStatusRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
