# This file was auto-generated by Fern from our API Definition.

from ..core.unchecked_base_model import UncheckedBaseModel
from .agent_linked_file_response import AgentLinkedFileResponse
from .agent_log_response import AgentLogResponse
from .agent_response import AgentResponse
from .evaluator_log_response import EvaluatorLogResponse
from .evaluator_response import EvaluatorResponse
from .flow_log_response import FlowLogResponse
from .flow_response import FlowResponse
from .monitoring_evaluator_response import MonitoringEvaluatorResponse
from .prompt_log_response import PromptLogResponse
from .prompt_response import PromptResponse
from .tool_log_response import ToolLogResponse
from .tool_response import ToolResponse
from .version_deployment_response import VersionDeploymentResponse
from .version_id_response import VersionIdResponse
import typing
from .agent_continue_stream_response_payload import AgentContinueStreamResponsePayload
from .event_type import EventType
import datetime as dt
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class AgentContinueStreamResponse(UncheckedBaseModel):
    """
    Response model for continuing an Agent call in streaming mode.
    """

    log_id: str
    message: str
    payload: typing.Optional[AgentContinueStreamResponsePayload] = None
    type: EventType
    created_at: dt.datetime

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
