# This file was auto-generated by Fern from our API Definition.

import typing
from .open_ai_reasoning_effort import OpenAiReasoningEffort

AgentResponseReasoningEffort = typing.Union[OpenAiReasoningEffort, int]
