# This file was auto-generated by Fern from our API Definition.

from ..core.unchecked_base_model import UncheckedBaseModel
import pydantic
import typing
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class CreatePromptLogResponse(UncheckedBaseModel):
    id: str = pydantic.Field()
    """
    String ID of log.
    """

    prompt_id: str = pydantic.Field()
    """
    ID of the Prompt the log belongs to.
    """

    version_id: str = pydantic.Field()
    """
    ID of the specific version of the Prompt.
    """

    session_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    String ID of session the log belongs to.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
