# This file was auto-generated by Fern from our API Definition.

import typing

EvaluatorReturnTypeEnum = typing.Union[
    typing.Literal["boolean", "number", "select", "multi_select", "text"], typing.Any
]
