# This file was auto-generated by Fern from our API Definition.

import typing

from .evaluator_response import EvaluatorResponse
from .prompt_response import PromptResponse
from .tool_response import ToolResponse

EvaluatedVersionResponse = typing.Union[PromptResponse, ToolResponse, EvaluatorResponse]
