# This file was auto-generated by Fern from our API Definition.

import typing

from .monitoring_evaluator_environment_request import MonitoringEvaluatorEnvironmentRequest
from .monitoring_evaluator_version_request import MonitoringEvaluatorVersionRequest

EvaluatorActivationDeactivationRequestActivateItem = typing.Union[
    MonitoringEvaluatorVersionRequest, MonitoringEvaluatorEnvironmentRequest
]
