# This file was auto-generated by Fern from our API Definition.

import typing

FilesToolType = typing.Union[
    typing.Literal["pinecone_search", "google", "mock", "snippet", "json_schema", "get_api_call"], typing.Any
]
