# This file was auto-generated by Fern from our API Definition.

import typing

from .agent_log_stream_response import AgentLogStreamResponse
from .prompt_call_stream_response import PromptCallStreamResponse

LogStreamResponse = typing.Union[PromptCallStreamResponse, AgentLogStreamResponse]
