# This file was auto-generated by Fern from our API Definition.

from ..core.unchecked_base_model import UncheckedBaseModel
import typing
from .datapoint_response import DatapointResponse
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class PaginatedDatapointResponse(UncheckedBaseModel):
    records: typing.List[DatapointResponse]
    page: int
    size: int
    total: int

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
